# Aliases for the zypper package manager
alias zypsh='sudo zypper sh' # Accept multiple commands at once
alias zyplr='zypper lr' # List repos
alias zypar='sudo zypper ar' # Add repo
alias zyprr='sudo zypper rr' # Remove repo
alias zypnr='sudo zypper nr' # Rename repo
alias zypmr='sudo zypper mr' # Modify repo
alias zypref='sudo zypper ref' # Refresh all repos
alias zypcc='sudo zypper cc' # Clean local caches
alias zypls='zypper ls' # List all defined services
alias zypas='sudo zypper as' # Add a new service
alias zypms='sudo zypper ms' # Modify specified service
alias zyprs='sudo zypper rs' # Remove specified service
alias zyprefs='sudo zypper refs' # Refresh all services
alias zypin='sudo zypper in' # Install packages
alias zyprm='sudo zypper rm' # Remove packages
alias zyprmptf='sudo zypper rmptf' # Remove (not only) PTFs
alias zypve='sudo zypper ve' # Verify integrity of package dependencies
alias zypsi='sudo zypper si' # Install source packages and their build dependencies
alias zypinr='sudo zypper inr' # Install newly added packages recommended by installed packages
alias zypup='sudo zypper up' # Update installed packages
alias zyplu='zypper lu' # List available updates
alias zyplp='zypper lp' # List available patches
alias zyppatch='sudo zypper patch' # Install needed patches
alias zypdup='sudo zypper dup' # Perform a distribution upgrade
alias zyppchk='zypper pchk' # Check for patches
alias zypse='zypper se' # Search for packages
alias zypif='zypper if' # Show full information for specified packages
alias zyppchif='zypper patch-info' # Show full information for specified patches
alias zypptif='zypper pattern-info' # Show full information for specified patterns
alias zyppdif='zypper product-info' # Show full information for specified products
alias zyppch='zypper pch' # List all available patches 
alias zyppa='zypper pa' # List all available packages
alias zyppt='zypper pt' # List all available patterns
alias zyppd='zypper pd' # List all available products
alias zypwp='zypper wp' # List packages providing specified capability
alias zypal='sudo zypper al' # Add a package lock
alias zyprl='sudo zypper rl' # Remove a package lock
alias zypll='zypper ll' # List current package locks
alias zypcl='sudo zypper cl' # Remove useless locks
alias zyplloc='zypper lloc' # List requested locales
alias zypaloc='sudo zypper aloc' # Add locale(s) to requested locales
alias zyprloc='sudo zypper rloc' # Remove locale(s) from requested locales
alias zypvcmp='zypper vcmp' # Compare two version strings
alias zyptos='zypper tos' # Print the target operating system ID string
alias zyplic='zypper licenses' # Print report about licenses and EULAs of installed packages
alias zypdl='sudo zypper download' # Download rpms specified on the commandline to a local directory
alias zypsdl='sudo zypper source-download' # Download source rpms for all installed packages to a local directory
alias zypnr='zypper needs-rebooting' # Check if the reboot-needed flag was set
alias zypps='zypper ps' # List running processes which might still use files and libraries deleted by recent upgrades
alias zyppk='sudo zypper purge-kernels' # Remove old kernels
